"""add_company_model_and_update_job_user_relationships

Revision ID: c3dcab6e46d6
Revises: 3d1a9d2c0800
Create Date: 2025-09-13 00:24:04.214781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dcab6e46d6'
down_revision = '3d1a9d2c0800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create companies table
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    
    # Add company_id column to users table (nullable for candidates)
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    
    # Add company_id column to jobs table (nullable first)
    op.add_column('jobs', sa.Column('company_id', sa.UUID(), nullable=True))
    
    # Create a default company for existing jobs
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO companies (id, name, description, created_at) 
        VALUES (gen_random_uuid(), 'Default Company', 'Default company for existing jobs', now())
    """))
    
    # Get the default company ID
    result = connection.execute(sa.text("SELECT id FROM companies WHERE name = 'Default Company' LIMIT 1"))
    default_company_id = result.fetchone()[0]
    
    # Update existing jobs to use the default company
    connection.execute(sa.text(f"""
        UPDATE jobs SET company_id = '{default_company_id}'
    """))
    
    # Now make company_id non-nullable
    op.alter_column('jobs', 'company_id', nullable=False)
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'])
    
    # Drop the old company column
    op.drop_column('jobs', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.add_column('jobs', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_id')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###































